import { signIn, useSession } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  const { data: session } = useSession();

  console.log(session);
  return (
    <>
      <Head>
        <title>Realz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Join application</h1>
        <button onClick={() => signIn("github")}>Sign in github</button>
      </main>
    </>
  );
}
